# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================
spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NWRlNDg3YzM2OGU4MWU4MWQwZWVmZGNjZGZlNWQxZDIxMGEzYmFjNjU0ZDM2NjI5NTA2YzU3MmYyMDdiYjkwN2FlNWY0MDdlZmI4ODFmMzhkMTAxYTUzMDIxOWY2MmZiMTg3Zjc1N2IwMzA1YzMxMGE5NmU2ZGJkN2Q3MmQ1NjU=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: smartpark
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: smartpark
    password:
