package com.tusofia.smartpark.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParkingSpotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkingSpotAllPropertiesEquals(ParkingSpot expected, ParkingSpot actual) {
        assertParkingSpotAutoGeneratedPropertiesEquals(expected, actual);
        assertParkingSpotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkingSpotAllUpdatablePropertiesEquals(ParkingSpot expected, ParkingSpot actual) {
        assertParkingSpotUpdatableFieldsEquals(expected, actual);
        assertParkingSpotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkingSpotAutoGeneratedPropertiesEquals(ParkingSpot expected, ParkingSpot actual) {
        assertThat(actual)
            .as("Verify ParkingSpot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkingSpotUpdatableFieldsEquals(ParkingSpot expected, ParkingSpot actual) {
        assertThat(actual)
            .as("Verify ParkingSpot relevant properties")
            .satisfies(a -> assertThat(a.getDateCreated()).as("check dateCreated").isEqualTo(expected.getDateCreated()))
            .satisfies(a -> assertThat(a.getSlotNumber()).as("check slotNumber").isEqualTo(expected.getSlotNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkingSpotUpdatableRelationshipsEquals(ParkingSpot expected, ParkingSpot actual) {
        // empty method
    }
}
