export const carBrands: Record<string, string> = {
  BMW: "bmw",
  "Mercedes-Benz": "mercedes-benz",
  Toyota: "toyota",
  Honda: "honda",
  Ford: "ford",
  Chevrolet: "chevrolet",
  Volkswagen: "volkswagen",
  Audi: "audi",
  Hyundai: "hyundai",
  Nissan: "nissan",
  Kia: "kia",
  Subaru: "subaru",
  Mazda: "mazda",
  Lexus: "lexus",
  Jeep: "jeep",
  Dodge: "dodge",
};